### ISSUE TITLE
支持Travis CI

### ISSUE THREAD

**Issue by voidint** [voidint/g#13]
```yaml
language: go

sudo: false

go:
    - master

before_install:
    - go get github.com/mattn/goveralls

script:
    - GOOS=darwin go build
    - GOOS=windows go build
    - GOOS=linux go build
    - $HOME/gopath/bin/goveralls -service=travis-ci
```
