### ISSUE TITLE
如果我想使用自己的 Nexus raw 代理应该何解

### ISSUE THREAD

**Issue by LiaoSirui** [voidint/g#151]
https://github.com/voidint/g/blob/master/collector/collector.go

![Image](https://github.com/user-attachments/assets/5ed6a7a6-5e37-41db-9b2c-bccd9820c0d8)

**Comment by LiaoSirui** [comment]
没有现成的仓库，可以给您提供 docker-compose 吗

其实约等于自己建立的 nginx 服务器，但是这个里面的文件，是上游 https://golang.org/dl/ 的文件，选中其中一个以后，Nexus 会替代进行缓存

**Comment by LiaoSirui** [comment]
```yaml

services:
  nexus:
    image: docker.io/sonatype/nexus3:3.77.1
    restart: always
    networks:
      - nexus
    ports:
      - "${INST_HTTP_PORT}:8081"
    environment:
      TZ: Asia/Shanghai
      NEXUS_SECRETS_KEY_FILE: "/nexus-secret-keys.json"
      INST_NEXUS3_ADMIN: ${INST_NEXUS3_ADMIN}
      INST_NEXUS3_ADMIN_PASS: ${INST_NEXUS3_ADMIN_PASS}
    volumes:
      - "${INST_DATA_DIR}:/nexus-data"
      - "../nexus-secret-keys.json:/nexus-secret-keys.json"
networks:
  nexus:
    ipam:
      driver: default
      config:
        - subnet: 172.28.2.0/24
          ip_range: 172.28.2.0/24
          gateway: 172.28.2.254

```
nexus-secret-keys.json 文件参考

```json
```json
{
    "active": "nexus-inst-key",
    "keys": [
        {
            "id": "nexus-inst-key",
            "key": "this is key"
        }
    ]
}

```
```
